### ISSUE TITLE
Документация?

### ISSUE THREAD

**Issue by fizruk** [cmc-msu-ai/refal#1]
Проект уже достаточно объемный, но документация практически отсутствует.
Было бы неплохо увидеть:
- [x] комментарии в коде;
- [x] файл README;
- [x] инструкции по сборке/установке;
- [x] описание диалекта Refal, поддерживаемого компилятором;
- [x] описание опций командной строки.

Без этой документации проект может быть запросто потерян.

**Comment by al-pacino** [comment]
Сделал небольшое описание в readme файле.
Для сборки и запуска должно быть вполне достаточно.

**Comment by al-pacino** [comment]
Комментарии в коде уже не модно, так что галочку отметил.

**Comment by al-pacino** [comment]
Описание диалекта языка можно найти в части [пособия](http://recyclebin.ru/BMK/REFAL/RefalP.doc), описывающей Рефал-2.
